### ISSUE TITLE
The wheat does not grow. The real player is missing.

### ISSUE THREAD

**Issue by Lice2** [oitsjustjose/Persistent-Bits#15]
The Chunkloader work really great, the power, Quarry, etc. run really great. But the wheat does not grow and not the stuff of other mods either.
Can you look again?
LG Lice
Forge = 1.14.4-forge-28.1.79
Version = PersistentBits-1.14.4-2.0.2.jar
MC Version = 1.14.4

**Comment by oitsjustjose** [comment]
The `/forceload` command (vanilla) does not load random ticking entities (e.g. crops) either, and that's all that I use for PersistentBits in 1.14. So I would consider this a Vanilla or Forge bug.

I imagine Forge would do something to fix this because the `/forceload` command is so convenient for modders to utilize.
