### ISSUE TITLE
[Suggestion] Config option for chunkloading only when player is on

### ISSUE THREAD

**Issue by Carrots4U** [oitsjustjose/Persistent-Bits#4]
Please add a config to only allow chunkloading to work when the player is online. It'd really help laggy servers with many chunkloaders.

**Comment by oitsjustjose** [comment]
Hmmmmmmmmmm.... I'll have to look into this. Chunk Loaders should be restricted in other ways perhaps, like allowing only a server OP to place them (configurable) instead of limiting one to only work with online players. 

I only suggest other solutions because this solution directly is going to be incredibly difficult. I'd have to not only track when players log off and log on, I'd have to find a way to track where they've placed chunk loaders, invalidate the loaders when they leave  AND validate them when they join.

Let me know your thoughts on limiting chunk loaders on SMP to only being placed by Operators (configurable, like I said) as a way to reduce chunk loading lag.

**Comment by Carrots4U** [comment]
How about a config option to make them run on ender pearls, but not be able to automate the piping in (like personal anchor from Railcraft)? That way when they run out of fuel a person would have to manually replace the fuel. Your way might be helpful, but I wouldn't be able to use it because I help run a server on the more bigger side, and I wouldn't be able to single handily place a chunkloader for someone when they need it.

**Comment by oitsjustjose** [comment]
That's be no easy feature either, since they aren't ticking tile entities right now, but that would require them to be... 

I know this feature has been seen in a few other chunk loaders, but is chunk loading really that big of a concern? I understand that it causes lag, but only if what it's loading is a ridiculous build in the first place. On my server (running on a Mac Mini Server as far as hardware goes) we have them and haven't experienced any lag at our bases, with Refined Storage systems, nether pumps and RFTools excavation sites. 

My last concern is that this complicates the mod itself and steps away from the original concept of it - 

> Persistent Bits is a very simple, no-fuel-required Chunk Loading mod. 

Sort of seems like these solutions are steps in the opposite direction of the mod's "mission statement". Side note though, I've heard that RailCraft will be releasing an update soon (hopefully in the next month is my guess, but that's not been told to me by anyone), so perhaps personal anchors might be what you're looking for when the server gets to that point in lag.

**Comment by Carrots4U** [comment]
I understand, if you ever reconsider let me know.
